/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* Name of package */
#define PACKAGE "cnver"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "cnver@cs.toronto.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "cnver"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "cnver 0.8.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cnver"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.8.1"

/* Version number of package */
#define VERSION "0.8.1"
